#Each new term in the Fibonacci sequence is generated by adding the previous two terms.
# By starting with 1 and 2, the first 10 terms will be:
#1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
#By considering the terms in the Fibonacci sequence whose values do not exceed four million,
# find the sum of the even-valued terms.

def evenFibonacciNumbers():
    FOURMILLION = 4000000

    #The inition of the Fibonacci List is 1 and 2
    listOfFibonacci =[1,2]
    count = 1
    while listOfFibonacci[count-1]+listOfFibonacci[count] < FOURMILLION:
        #Appending the sum of two last numbers
        listOfFibonacci.append(listOfFibonacci[count-1]+listOfFibonacci[count])
        count+=1
    return listOfFibonacci

print(evenFibonacciNumbers())